name: Docs deploy

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: npm install
        run: npm ci
      - name: build docs
        run: npx typedoc
      - name: Copy docs to Toolforge (twinkle.toolforge.org)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/twinkle-core/twinkle-core/docs
          remote: /data/project/twinkle/public_html/core-docs
          host: login.toolforge.org
          username: ${{ secrets.TOOLFORGE_USERNAME }}
          privateKey: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}
          rmRemote: true
          dotfiles: true
      - name: Copy docs to Toolforge (tools-static.wmflabs.org/twinkle)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/twinkle-core/twinkle-core/docs
          remote: /data/project/twinkle/www/static/core-docs
          host: login.toolforge.org
          username: ${{ secrets.TOOLFORGE_USERNAME }}
          privateKey: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}
          rmRemote: true
          dotfiles: true
