name: Docs deploy

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: parent working directory
        run: pwd
      - name: Copy docs to Toolforge
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/twinkle-core/twinkle-core/docs
          remote: /data/project/twinkle/www/static/core-docs
          host: login.toolforge.org
          username: ${{ secrets.TOOLFORGE_USERNAME }}
          privateKey: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}
          rmRemote: true
          dotfiles: true
